movies_data = [
    {'title': 'Se7en', 'genre': 'Thriller', 'ranking': 1},
    {'title': 'The Silence of the Lambs', 'genre': 'Thriller', 'ranking': 2},
    {'title': 'Shutter Island', 'genre': 'Thriller', 'ranking': 3},
    {'title': 'The Sixth Sense', 'genre': 'Thriller', 'ranking': 4},
    {'title': 'Zodiac', 'genre': 'Thriller', 'ranking': 5},
    {'title': 'Inception', 'genre': 'Thriller', 'ranking': 6},
    {'title': 'North by Northwest', 'genre': 'Thriller', 'ranking': 7},
    {'title': 'Beauty and the Beast', 'genre': 'Romance', 'ranking': 1},
    {'title': 'Her', 'genre': 'Romance', 'ranking': 2},
    {'title': 'Eternal Sunshine of the Spotless Mind', 'genre': 'Romance', 'ranking': 3},
    {'title': 'Casablanca', 'genre': 'Romance', 'ranking': 4},
    {'title': 'Before Sunrise', 'genre': 'Romance', 'ranking': 5},
    {'title': 'In the Mood for Love', 'genre': 'Romance', 'ranking': 6},
    {'title': 'Brokeback Mountain', 'genre': 'Romance', 'ranking': 7},
    {'title': 'Saving Private Ryan', 'genre': 'War', 'ranking': 1},
    {'title': 'Apocalypse Now', 'genre': 'War', 'ranking': 2},
    {'title': 'Full Metal Jacket', 'genre': 'War', 'ranking': 3},
    {'title': 'Platoon', 'genre': 'War', 'ranking': 4},
    {'title': 'Dunkirk', 'genre': 'War', 'ranking': 5},
    {'title': 'The Thin Red Line', 'genre': 'War', 'ranking': 6},
    {'title': 'Paths of Glory', 'genre': 'War', 'ranking': 7},
    {'title': 'Once Upon a Time in America', 'genre': 'Crime', 'ranking': 1},
    {'title': 'L.A. Confidential', 'genre': 'Crime', 'ranking': 2},
    {'title': 'Chinatown', 'genre': 'Crime', 'ranking': 3},
    {'title': 'The Debt', 'genre': 'Crime', 'ranking': 4},
    {'title': 'The Killing', 'genre': 'Crime', 'ranking': 5},
    {'title': 'Double Indemnity', 'genre': 'Crime', 'ranking': 6},
    {'title': 'Elevator to the Gallows', 'genre': 'Crime', 'ranking': 7},
    {'title': 'Blackfish', 'genre': 'Documentary', 'ranking': 1},
    {'title': 'Exit Through the Gift Shop', 'genre': 'Documentary', 'ranking': 2},
    {'title': 'Dear Zachary: A Letter to a Son About His Father', 'genre': 'Documentary', 'ranking': 3},
    {'title': 'Grizzly Man', 'genre': 'Documentary', 'ranking': 4},
    {'title': 'Samsara', 'genre': 'Documentary', 'ranking': 5},
    {'title': 'O.J.: Made in America', 'genre': 'Documentary', 'ranking': 6},
    {'title': 'Free Solo', 'genre': 'Documentary', 'ranking': 7}
]
